/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { RivetRivet } from "@fern-api/rivet";
import * as core from "../../../../core";

export const Response: core.schemas.Schema<
  serializers.identity.listFollowers.Response.Raw,
  RivetRivet.ListFollowersOutput
> = core.schemas.lazyObject(async () => (await import("../../..")).ListFollowersOutput);

export declare namespace Response {
  type Raw = serializers.ListFollowersOutput.Raw;
}
