/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { RivetRivet } from "@fern-api/rivet";
import * as core from "../../../../core";

export const Request: core.schemas.Schema<
  serializers.identity.setGameActivity.Request.Raw,
  RivetRivet.SetIdentityGameActivityInput
> = core.schemas.object({
  gameActivity: core.schemas.property(
    "game_activity",
    core.schemas.lazyObject(async () => (await import("../../..")).identity.UpdateIdentityGameActivity)
  ),
});

export declare namespace Request {
  interface Raw {
    game_activity: serializers.identity.UpdateIdentityGameActivity.Raw;
  }
}
