/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { RivetApi } from "@fern-api/rivet";
import * as core from "../../../../core";

export const Request: core.schemas.Schema<serializers.identity.signupForBeta.Request.Raw, RivetApi.SignupForBetaInput> =
  core.schemas.object({
    name: core.schemas.string(),
    companyName: core.schemas.property("company_name", core.schemas.string().optional()),
    companySize: core.schemas.property("company_size", core.schemas.string()),
    preferredTools: core.schemas.property("preferred_tools", core.schemas.string()),
    goals: core.schemas.string(),
  });

export declare namespace Request {
  interface Raw {
    name: string;
    company_name?: string | null;
    company_size: string;
    preferred_tools: string;
    goals: string;
  }
}
