/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { RivetApi } from "@fern-api/rivet";
import * as core from "../../../../core";

export const Request: core.serialization.Schema<
    serializers.identity.updateIdentityStatus.Request.Raw,
    RivetApi.UpdateIentityStatusInput
> = core.serialization.object({
    status: core.serialization.lazy(async () => (await import("../../..")).commons.IdentityStatus),
});

export declare namespace Request {
    interface Raw {
        status: serializers.commons.IdentityStatus.Raw;
    }
}
