/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PutInput {
    /** A universally unique identifier. */
    namespaceId?: string;
    /** Any JSON value to set the key to. */
    key: string;
}
