/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../..";
import { Rivet } from "@rivet-gg/api";
import * as core from "../../../../../../../../core";

export const ExportMatchmakerLobbyHistoryRequest: core.serialization.ObjectSchema<
    serializers.cloud.games.ExportMatchmakerLobbyHistoryRequest.Raw,
    Rivet.cloud.games.ExportMatchmakerLobbyHistoryRequest
> = core.serialization.object({
    queryStart: core.serialization.property("query_start", core.serialization.number().optional()),
    queryEnd: core.serialization.property("query_end", core.serialization.number().optional()),
});

export declare namespace ExportMatchmakerLobbyHistoryRequest {
    interface Raw {
        query_start?: number | null;
        query_end?: number | null;
    }
}
