/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../..";
import { Rivet } from "@rivet-gg/api";
import * as core from "../../../../../../../../core";

export const ExportLobbyLogsOutput: core.serialization.ObjectSchema<
    serializers.cloud.games.ExportLobbyLogsOutput.Raw,
    Rivet.cloud.games.ExportLobbyLogsOutput
> = core.serialization.object({
    url: core.serialization.string(),
});

export declare namespace ExportLobbyLogsOutput {
    interface Raw {
        url: string;
    }
}
