/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { Rivet } from "@rivet-gg/api";
import * as core from "../../../../../../core";

export const AnalyticsVariantQuery: core.serialization.Schema<
    serializers.cloud.AnalyticsVariantQuery.Raw,
    Rivet.cloud.AnalyticsVariantQuery
> = core.serialization.enum_([
    "matchmaker_overview",
    "player_count",
    "player_count_by_region",
    "player_count_by_game_mode",
    "lobby_count",
    "lobby_count_by_region",
    "lobby_count_by_game_mode",
    "avg_play_duration",
    "avg_play_duration_by_region",
    "avg_play_duration_by_game_mode",
    "new_players_per_second",
    "new_lobbies_per_second",
    "destroyed_lobbies_by_failure",
    "destroyed_lobbies_by_exit_code",
    "failed_lobbies",
    "lobby_ready_time",
    "identity_accounts",
]);

export declare namespace AnalyticsVariantQuery {
    type Raw =
        | "matchmaker_overview"
        | "player_count"
        | "player_count_by_region"
        | "player_count_by_game_mode"
        | "lobby_count"
        | "lobby_count_by_region"
        | "lobby_count_by_game_mode"
        | "avg_play_duration"
        | "avg_play_duration_by_region"
        | "avg_play_duration_by_game_mode"
        | "new_players_per_second"
        | "new_lobbies_per_second"
        | "destroyed_lobbies_by_failure"
        | "destroyed_lobbies_by_exit_code"
        | "failed_lobbies"
        | "lobby_ready_time"
        | "identity_accounts";
}
