/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { Rivet } from "@rivet-gg/api";
import * as core from "../../../../../../core";

export const LobbyCountDataSet: core.serialization.ObjectSchema<
    serializers.cloud.LobbyCountDataSet.Raw,
    Rivet.cloud.LobbyCountDataSet
> = core.serialization.object({
    ts: core.serialization.list(core.serialization.number()),
    lobbyCount: core.serialization.property("lobby_count", core.serialization.list(core.serialization.number())),
    lobbyPreemptiveCount: core.serialization.property(
        "lobby_preemptive_count",
        core.serialization.list(core.serialization.number())
    ),
    lobbyUnreadyCount: core.serialization.property(
        "lobby_unready_count",
        core.serialization.list(core.serialization.number())
    ),
    lobbyClosedCount: core.serialization.property(
        "lobby_closed_count",
        core.serialization.list(core.serialization.number())
    ),
});

export declare namespace LobbyCountDataSet {
    interface Raw {
        ts: number[];
        lobby_count: number[];
        lobby_preemptive_count: number[];
        lobby_unready_count: number[];
        lobby_closed_count: number[];
    }
}
