/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { Rivet } from "@rivet-gg/api";
import * as core from "../../../../../../core";

export const LobbyCountByRegionDataSet: core.serialization.ObjectSchema<
    serializers.cloud.LobbyCountByRegionDataSet.Raw,
    Rivet.cloud.LobbyCountByRegionDataSet
> = core.serialization.object({
    ts: core.serialization.list(core.serialization.number()),
    regionNameId: core.serialization.property("region_name_id", core.serialization.list(core.serialization.string())),
    lobbyCount: core.serialization.property("lobby_count", core.serialization.list(core.serialization.number())),
});

export declare namespace LobbyCountByRegionDataSet {
    interface Raw {
        ts: number[];
        region_name_id: string[];
        lobby_count: number[];
    }
}
