/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors";
import * as Rivet from "../../..";

export class ForbiddenError extends errors.RivetError {
    constructor(body: Rivet.ErrorBody) {
        super({
            statusCode: 403,
            body: body,
        });
        Object.setPrototypeOf(this, ForbiddenError.prototype);
    }
}
