/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetSummaryRequest {
    /**
     * A query parameter denoting the requests watch index.
     */
    watchIndex?: string;
}
