/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../..";
import { Rivet } from "@rivet-gg/api";
import * as core from "../../../../../../../../core";

export const CreateGameCdnSiteOutput: core.serialization.ObjectSchema<
    serializers.cloud.games.CreateGameCdnSiteOutput.Raw,
    Rivet.cloud.games.CreateGameCdnSiteOutput
> = core.serialization.object({
    siteId: core.serialization.property("site_id", core.serialization.string()),
    uploadId: core.serialization.property("upload_id", core.serialization.string()),
    presignedRequests: core.serialization.property(
        "presigned_requests",
        core.serialization.list(
            core.serialization.lazyObject(async () => (await import("../../../../../../..")).upload.PresignedRequest)
        )
    ),
});

export declare namespace CreateGameCdnSiteOutput {
    interface Raw {
        site_id: string;
        upload_id: string;
        presigned_requests: serializers.upload.PresignedRequest.Raw[];
    }
}
