/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Rivet } from "@rivet-gg/api";

export interface GetStatisticsResponse {
    playerCount: number;
    gameModes: Record<Rivet.Identifier, Rivet.matchmaker.GameModeStatistics>;
}
