/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Rivet } from "@rivet-gg/api";

export interface Handle {
    gameId: string;
    nameId: Rivet.Identifier;
    displayName: Rivet.DisplayName;
    logoUrl: string;
    bannerUrl: string;
}
