/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { RivetApi } from "@fern-api/rivet";

/**
 * Represents the topic of the given chat thread.
 */
export type ChatTopic =
  | RivetApi.commons.ChatTopic.Group
  | RivetApi.commons.ChatTopic.Party
  | RivetApi.commons.ChatTopic.Direct
  | RivetApi.commons.ChatTopic._Unknown;

export declare namespace ChatTopic {
  interface Group extends RivetApi.commons.ChatTopicGroup, _Utils {
    type: "group";
  }

  interface Party extends RivetApi.commons.ChatTopicParty, _Utils {
    type: "party";
  }

  interface Direct extends RivetApi.commons.ChatTopicDirect, _Utils {
    type: "direct";
  }

  interface _Unknown extends _Utils {
    type: void;
  }

  interface _Utils {
    _visit: <_Result>(visitor: RivetApi.commons.ChatTopic._Visitor<_Result>) => _Result;
  }

  interface _Visitor<_Result> {
    group: (value: RivetApi.commons.ChatTopicGroup) => _Result;
    party: (value: RivetApi.commons.ChatTopicParty) => _Result;
    direct: (value: RivetApi.commons.ChatTopicDirect) => _Result;
    _other: (value: { type: string }) => _Result;
  }
}

export const ChatTopic = {
  group: (value: RivetApi.commons.ChatTopicGroup): RivetApi.commons.ChatTopic.Group => {
    return {
      ...value,
      type: "group",
      _visit: function <_Result>(
        this: RivetApi.commons.ChatTopic.Group,
        visitor: RivetApi.commons.ChatTopic._Visitor<_Result>
      ) {
        return RivetApi.commons.ChatTopic._visit(this, visitor);
      },
    };
  },

  party: (value: RivetApi.commons.ChatTopicParty): RivetApi.commons.ChatTopic.Party => {
    return {
      ...value,
      type: "party",
      _visit: function <_Result>(
        this: RivetApi.commons.ChatTopic.Party,
        visitor: RivetApi.commons.ChatTopic._Visitor<_Result>
      ) {
        return RivetApi.commons.ChatTopic._visit(this, visitor);
      },
    };
  },

  direct: (value: RivetApi.commons.ChatTopicDirect): RivetApi.commons.ChatTopic.Direct => {
    return {
      ...value,
      type: "direct",
      _visit: function <_Result>(
        this: RivetApi.commons.ChatTopic.Direct,
        visitor: RivetApi.commons.ChatTopic._Visitor<_Result>
      ) {
        return RivetApi.commons.ChatTopic._visit(this, visitor);
      },
    };
  },

  _unknown: (value: { type: string }): RivetApi.commons.ChatTopic._Unknown => {
    return {
      ...(value as any),
      _visit: function <_Result>(
        this: RivetApi.commons.ChatTopic._Unknown,
        visitor: RivetApi.commons.ChatTopic._Visitor<_Result>
      ) {
        return RivetApi.commons.ChatTopic._visit(this, visitor);
      },
    };
  },

  _visit: <_Result>(
    value: RivetApi.commons.ChatTopic,
    visitor: RivetApi.commons.ChatTopic._Visitor<_Result>
  ): _Result => {
    switch (value.type) {
      case "group":
        return visitor.group(value);
      case "party":
        return visitor.party(value);
      case "direct":
        return visitor.direct(value);
      default:
        return visitor._other(value as any);
    }
  },
} as const;
