/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { RivetRivet } from "@fern-api/rivet";

/**
 * A chat thread
 */
export interface ChatThread {
  threadId: string;
  createTs: RivetRivet.commons.Timestamp;
  topic: RivetRivet.commons.ChatTopic;
  tailMessage?: RivetRivet.commons.ChatMessage;
  lastReadTs: RivetRivet.commons.Timestamp;
  unreadCount: number;
  external: RivetRivet.commons.ChatThreadExternalLinks;
}
