/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { RivetApi } from "@fern-api/rivet";

export interface ChatMessage {
  chatMessageId: string;
  threadId: string;
  sendTs: RivetApi.commons.Timestamp;
}
