/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Rivet } from "@rivet-gg/api";

export interface CreateGameCdnSiteOutput {
    /** A universally unique identifier. */
    siteId: string;
    /** A universally unique identifier. */
    uploadId: string;
    presignedRequests: Rivet.upload.PresignedRequest[];
}
