/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { RivetIdentity } from "@fern-api/rivet-identity";

/**
 * An error thrown when the requestee has sent an invalid or malformed request.
 */
export type BadRequestError = RivetIdentity.BadRequestErrorResponseContent;
