/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { RivetIdentity } from "@fern-api/rivet-identity";

/**
 * An error thrown when the requestee requests a resource they do not have access to.
 */
export type ForbiddenError = RivetIdentity.ForbiddenErrorResponseContent;
