/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { RivetIdentity } from "@fern-api/rivet-identity";

/**
 * An error caused by internal server problems.
 */
export type InternalError = RivetIdentity.InternalErrorResponseContent;
