/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { RivetIdentity } from "@fern-api/rivet-identity";

/**
 * An error thrown when the requestee is not authenticated.
 */
export type UnauthorizedError = RivetIdentity.UnauthorizedErrorResponseContent;
