/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { RivetIdentity } from "@fern-api/rivet-identity";

export interface BaseError {
  code: string;
  message: string;
  metadata?: RivetIdentity.ErrorMetadata | undefined;
}
