/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { RivetApi } from "@fern-api/rivet";
import * as core from "../../../../../../core";

export const ChatTopicDirect: core.serialization.ObjectSchema<
    serializers.commons.ChatTopicDirect.Raw,
    RivetApi.commons.ChatTopicDirect
> = core.serialization.object({
    identityA: core.serialization.property(
        "identity_a",
        core.serialization.lazyObject(async () => (await import("../../../../..")).commons.IdentityHandle)
    ),
    identityB: core.serialization.property(
        "identity_b",
        core.serialization.lazyObject(async () => (await import("../../../../..")).commons.IdentityHandle)
    ),
});

export declare namespace ChatTopicDirect {
    interface Raw {
        identity_a: serializers.commons.IdentityHandle.Raw;
        identity_b: serializers.commons.IdentityHandle.Raw;
    }
}
