/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { RivetRivet } from "@fern-api/rivet";
import * as core from "../../../../../../core";

export const ChatTopicParty: core.schemas.ObjectSchema<
  serializers.commons.ChatTopicParty.Raw,
  RivetRivet.commons.ChatTopicParty
> = core.schemas.object({
  party: core.schemas.lazyObject(async () => (await import("../../../../..")).commons.PartyHandle),
});

export declare namespace ChatTopicParty {
  interface Raw {
    party: serializers.commons.PartyHandle.Raw;
  }
}
