/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { RivetApi } from "@fern-api/rivet";
import * as core from "../../../../../../core";

export const ChatTopicParty: core.serialization.ObjectSchema<
    serializers.commons.ChatTopicParty.Raw,
    RivetApi.commons.ChatTopicParty
> = core.serialization.object({
    party: core.serialization.lazyObject(async () => (await import("../../../../..")).commons.PartyHandle),
});

export declare namespace ChatTopicParty {
    interface Raw {
        party: serializers.commons.PartyHandle.Raw;
    }
}
