/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { Rivet } from "@rivet-gg/api";
import * as core from "../../../../../../core";

export const GlobalEventChatThreadRemove: core.serialization.ObjectSchema<
    serializers.identity.GlobalEventChatThreadRemove.Raw,
    Rivet.identity.GlobalEventChatThreadRemove
> = core.serialization.object({
    threadId: core.serialization.property("thread_id", core.serialization.string()),
});

export declare namespace GlobalEventChatThreadRemove {
    interface Raw {
        thread_id: string;
    }
}
