/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Rivet } from "@rivet-gg/api";

/**
 * Turnstile captcha configuration.
 */
export interface CaptchaTurnstile {
    domains: Record<string, Rivet.cloud.version.matchmaker.CaptchaTurnstileDomain>;
}
