/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A proxy protocol.
 */
export type ProxyProtocol = "http" | "https" | "udp";

export const ProxyProtocol = {
    Http: "http",
    Https: "https",
    Udp: "udp",
} as const;
