/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetGroupInvoicesListRequest {
    /**
     * The pagination anchor. Set to the returned anchor of this endpoint to receive the next set of items.
     */
    anchor?: string;
    /**
     * Amount of invoices to return.
     */
    limit?: number;
}
