/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetGroupPaymentsListInput {
    /**
     * The payment ID of the payment after which to start listing.
     */
    startPaymentId?: string;
}
