/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetGroupTransfersListInput {
    /**
     * The transfer ID of the transfer after which to start listing.
     */
    startTransferId?: string;
}
