/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../..";
import { Rivet } from "@rivet-gg/api";
import * as core from "../../../../../../../../core";

export const GetGameVersionByIdOutput: core.serialization.ObjectSchema<
    serializers.cloud.games.GetGameVersionByIdOutput.Raw,
    Rivet.cloud.games.GetGameVersionByIdOutput
> = core.serialization.object({
    version: core.serialization.lazyObject(async () => (await import("../../../../../../..")).cloud.version.Full),
});

export declare namespace GetGameVersionByIdOutput {
    interface Raw {
        version: serializers.cloud.version.Full.Raw;
    }
}
