/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { RivetApi } from "@fern-api/rivet";

/**
 * A party activity denoting that the party is currently in a lobby.
 */
export interface PartyActivityMatchmakerLobby {
    lobby: RivetApi.commons.PartyMatchmakerLobby;
    game: RivetApi.commons.GameHandle;
}
