/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * External links for a party.
 */
export interface PartyExternalLinks {
  /** A link to the given party's chat thread. */
  chat: string;
}
