/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { RivetApi } from "@fern-api/rivet";

export interface PartyPublicity {
    public: RivetApi.commons.PartyPublicityLevel;
    mutualFollowers: RivetApi.commons.PartyPublicityLevel;
    groups: RivetApi.commons.PartyPublicityLevel;
}
