/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { RivetApi } from "@fern-api/rivet";
import * as core from "../../../../../../core";

export const GameModeInfo: core.serialization.ObjectSchema<
    serializers.matchmaker.GameModeInfo.Raw,
    RivetApi.matchmaker.GameModeInfo
> = core.serialization.object({
    gameModeId: core.serialization.property(
        "game_mode_id",
        core.serialization.lazy(async () => (await import("../../../../..")).commons.Identifier)
    ),
});

export declare namespace GameModeInfo {
    interface Raw {
        game_mode_id: serializers.commons.Identifier.Raw;
    }
}
