/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { RivetRivet } from "@fern-api/rivet";
import * as core from "../../../../core";

export const GetIdentitySummariesOutput: core.schemas.ObjectSchema<
  serializers.GetIdentitySummariesOutput.Raw,
  RivetRivet.GetIdentitySummariesOutput
> = core.schemas.object({
  identities: core.schemas.list(
    core.schemas.lazyObject(async () => (await import("../../..")).commons.IdentitySummary)
  ),
});

export declare namespace GetIdentitySummariesOutput {
  interface Raw {
    identities: serializers.commons.IdentitySummary.Raw[];
  }
}
