/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { RivetApi } from "@fern-api/rivet";
import * as core from "../../../../core";

export const ListMutualFriendsOutput: core.schemas.ObjectSchema<
  serializers.ListMutualFriendsOutput.Raw,
  RivetApi.ListMutualFriendsOutput
> = core.schemas.object({
  identities: core.schemas.list(core.schemas.lazyObject(async () => (await import("../../..")).commons.IdentityHandle)),
  anchor: core.schemas.string().optional(),
});

export declare namespace ListMutualFriendsOutput {
  interface Raw {
    identities: serializers.commons.IdentityHandle.Raw[];
    anchor?: string | null;
  }
}
