/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Rivet } from "@rivet-gg/api";
import * as core from "../../../../core";

export const ListRecentFollowersOutput: core.serialization.ObjectSchema<
    serializers.identity.ListRecentFollowersOutput.Raw,
    Rivet.identity.ListRecentFollowersOutput
> = core.serialization.object({
    identities: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("../../..")).identity.Handle)
    ),
    watch: core.serialization.lazyObject(async () => (await import("../../..")).WatchResponse),
});

export declare namespace ListRecentFollowersOutput {
    interface Raw {
        identities: serializers.identity.Handle.Raw[];
        watch: serializers.WatchResponse.Raw;
    }
}
