/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { RivetApi } from "@fern-api/rivet";
import * as core from "../../../../core";

export const SearchIdentitiesOutput: core.schemas.ObjectSchema<
  serializers.SearchIdentitiesOutput.Raw,
  RivetApi.SearchIdentitiesOutput
> = core.schemas.object({
  identities: core.schemas.list(core.schemas.lazyObject(async () => (await import("../../..")).commons.IdentityHandle)),
  anchor: core.schemas.string(),
});

export declare namespace SearchIdentitiesOutput {
  interface Raw {
    identities: serializers.commons.IdentityHandle.Raw[];
    anchor: string;
  }
}
