/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { RivetApi } from "@fern-api/rivet";
import * as core from "../../../../core";

export const ValidateIdentityProfileOutput: core.schemas.ObjectSchema<
  serializers.ValidateIdentityProfileOutput.Raw,
  RivetApi.ValidateIdentityProfileOutput
> = core.schemas.object({
  errors: core.schemas.list(core.schemas.lazyObject(async () => (await import("../../..")).commons.ValidationError)),
});

export declare namespace ValidateIdentityProfileOutput {
  interface Raw {
    errors: serializers.commons.ValidationError.Raw[];
  }
}
