/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { RivetApi } from "@fern-api/rivet";

export interface GetIdentityProfileInput {
  watchIndex?: RivetApi.commons.WatchQuery;
}
