/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ListFriendsInput {
  anchor?: string;
  /**
   * Range is between 1 and 32 (inclusive).
   */
  limit?: string;
}
