/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Rivet } from "@rivet-gg/api";

export interface ListRecentFollowersRequest {
    count?: number;
    watchIndex?: Rivet.WatchQuery | undefined;
}
