/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Rivet } from "@rivet-gg/api";

export interface UpdateProfileInput {
    displayName?: Rivet.DisplayName;
    accountNumber?: Rivet.AccountNumber;
    bio?: Rivet.Bio;
}
