/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Received any time the current identity is no longer able to access the  given thread. This can happen if the identity leaves a group or party.
 *
 */
export interface GlobalEventChatThreadRemove {
  threadId: string;
}
