/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { RivetRivet } from "@fern-api/rivet";

export interface GlobalEventIdentityUpdate {
  identity: RivetRivet.commons.IdentityProfile;
}
