/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../../../..";
import { Rivet } from "@rivet-gg/api";
import * as core from "../../../../../../../../../../core";

export const GetNamespaceAnalyticsMatchmakerLiveOutput: core.serialization.ObjectSchema<
    serializers.cloud.games.namespaces.GetNamespaceAnalyticsMatchmakerLiveOutput.Raw,
    Rivet.cloud.games.namespaces.GetNamespaceAnalyticsMatchmakerLiveOutput
> = core.serialization.object({
    lobbies: core.serialization.list(
        core.serialization.lazyObject(
            async () => (await import("../../../../../../../../..")).cloud.AnalyticsLobbySummary
        )
    ),
});

export declare namespace GetNamespaceAnalyticsMatchmakerLiveOutput {
    interface Raw {
        lobbies: serializers.cloud.AnalyticsLobbySummary.Raw[];
    }
}
