/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Rivet } from "@rivet-gg/api";

export interface GlobalEventKind {
    identityUpdate?: Rivet.identity.GlobalEventIdentityUpdate;
    matchmakerLobbyJoin?: Rivet.identity.GlobalEventMatchmakerLobbyJoin;
}
