/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Rivet } from "@rivet-gg/api";

/**
 * An event relevant to the current identity.
 */
export interface GlobalEvent {
    ts: Rivet.Timestamp;
    kind: Rivet.identity.GlobalEventKind;
    notification: Rivet.identity.GlobalEventNotification;
}
