/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { RivetApi } from "@fern-api/rivet";
import * as core from "../../../../../../core";

export const Bio: core.serialization.Schema<serializers.commons.Bio.Raw, RivetApi.commons.Bio> =
    core.serialization.string();

export declare namespace Bio {
    type Raw = string;
}
