/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { RivetApi } from "@fern-api/rivet";
import * as core from "../../../../../../core";

export const Timestamp: core.serialization.Schema<serializers.commons.Timestamp.Raw, RivetApi.commons.Timestamp> =
    core.serialization.string();

export declare namespace Timestamp {
    type Raw = string;
}
