/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { RivetIdentity } from "@fern-api/rivet-identity";

export interface GameHandle {
  gameId: string;
  nameId: RivetIdentity.Identifier;
  displayName: RivetIdentity.DisplayName;
  logUrl?: string;
  bannerUrl?: string;
}
