/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { RivetIdentity } from "@fern-api/rivet-identity";

export interface GetIdentityProfileOutput {
  identity: RivetIdentity.IdentityProfile;
  watch: RivetIdentity.WatchResponse;
}
