/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { RivetIdentity } from "@fern-api/rivet-identity";

export interface GroupHandle {
  groupId: string;
  displayName: RivetIdentity.DisplayName;
  /** The URL of this group's avatar image */
  avatarUrl: string;
  external: RivetIdentity.GroupExternalLinks;
  /** Whether or not this group is a developer group. */
  isDeveloper?: boolean;
}
