/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { RivetIdentity } from "@fern-api/rivet-identity";

export interface PartyHandle {
  partyId: string;
  createTs: Date;
  activity: RivetIdentity.PartyActivity;
  external: RivetIdentity.PartyExternalLinks;
}
