/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Rivet } from "@rivet-gg/api";

/**
 * A game mode runtime running through Docker.
 */
export interface GameModeRuntimeDocker {
    /** _Configures Rivet CLI behavior. Has no effect on server behavior._ */
    dockerfile?: string;
    /** _Configures Rivet CLI behavior. Has no effect on server behavior._ */
    image?: string;
    imageId?: string;
    args?: string[];
    env?: Record<string, string>;
    networkMode?: Rivet.cloud.version.matchmaker.NetworkMode;
    ports?: Record<string, Rivet.cloud.version.matchmaker.GameModeRuntimeDockerPort>;
}
