/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Rivet } from "@rivet-gg/api";

/**
 * A game mode region.
 */
export interface GameModeRegion {
    tier?: string;
    idleLobbies?: Rivet.cloud.version.matchmaker.GameModeIdleLobbiesConfig;
}
