/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Topic to send a chat message to.
 */
export interface SendTopic {
    threadId?: string;
    groupId?: string;
    partyId?: string;
    identityId?: string;
}
