/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Rivet from "../../../../..";

/**
 * Represents a topic of the given chat thread without the associated handles
 * for the topic.
 *
 */
export interface SimpleTopic {
    group?: Rivet.chat.SimpleTopicGroup;
    direct?: Rivet.chat.SimpleTopicDirect;
}
