/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Rivet from "../../../../..";

export interface TopicDirect {
    identityA: Rivet.identity.Handle;
    identityB: Rivet.identity.Handle;
}
