/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { RivetIdentity } from "@fern-api/rivet-identity";
import * as core from "../../../core";

export const BadRequestErrorResponseContent: core.schemas.ObjectSchema<
  serializers.BadRequestErrorResponseContent.Raw,
  RivetIdentity.BadRequestErrorResponseContent
> = core.schemas.object({}).extend(core.schemas.lazyObject(async () => (await import("../..")).BaseError));

export declare namespace BadRequestErrorResponseContent {
  interface Raw extends serializers.BaseError.Raw {}
}
