/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../..";
import { Rivet } from "@rivet-gg/api";
import * as core from "../../../../../../../core";

export const PlayerConnectedInput: core.serialization.Schema<
    serializers.matchmaker.PlayerConnectedInput.Raw,
    Rivet.matchmaker.PlayerConnectedInput
> = core.serialization.object({
    playerToken: core.serialization.property("player_token", core.serialization.string()),
});

export declare namespace PlayerConnectedInput {
    interface Raw {
        player_token: string;
    }
}
