/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { Rivet } from "@rivet-gg/api";
import * as core from "../../../../../../core";

export const PresignedRequest: core.serialization.ObjectSchema<
    serializers.upload.PresignedRequest.Raw,
    Rivet.upload.PresignedRequest
> = core.serialization.object({
    path: core.serialization.string(),
    url: core.serialization.string(),
});

export declare namespace PresignedRequest {
    interface Raw {
        path: string;
        url: string;
    }
}
