/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { RivetRivet } from "@fern-api/rivet";

export interface GameHandle {
  gameId: string;
  nameId: RivetRivet.commons.Identifier;
  displayName: RivetRivet.commons.DisplayName;
  logoUrl: string;
  bannerUrl: string;
}
