/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Configuration for creating a party invite.
 */
export interface CreateInviteConfig {
    /** An alias used to join a given party. This alias must be unique for all invites for your game. Pass this alias to `rivet.api.party.common#CreatedInvite$alias` to consume the invite. */
    alias?: string;
}
