/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Rivet } from "@rivet-gg/api";

/**
 * A party invite.
 */
export interface Invite {
    /** A universally unique identifier. */
    inviteId: string;
    /** RFC3339 timestamp. */
    createTs: Date;
    /**
     * A JSON Web Token.
     * Slightly modified to include a description prefix and use Protobufs of
     * JSON.
     */
    token: string;
    alias?: Rivet.party.InviteAlias;
    external: Rivet.party.InviteExternalLinks;
}
