/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Rivet } from "@rivet-gg/api";

export interface MemberSummary {
    identity: Rivet.identity.Handle;
    /** Whether or not this party member is the leader of the given party. */
    isLeader: boolean;
    joinTs: Date;
    state: Rivet.party.MemberState;
}
