/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Rivet } from "@rivet-gg/api";

export interface Profile {
    /** A universally unique identifier. */
    partyId: string;
    /** RFC3339 timestamp. */
    createTs: Date;
    activity: Rivet.party.Activity;
    external: Rivet.party.ExternalLinks;
    publicity: Rivet.party.Publicity;
    /** Unsigned 32 bit integer. */
    partySize?: number;
    /** A list of party members. */
    members: Rivet.party.MemberSummary[];
    /** A universally unique identifier. */
    threadId: string;
    /** A list of party invites. */
    invites: Rivet.party.Invite[];
}
