/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Rivet } from "@rivet-gg/api";

export interface Summary {
    partyId: string;
    createTs: Date;
    activity: Rivet.party.Activity;
    external: Rivet.party.ExternalLinks;
    publicity: Rivet.party.Publicity;
    partySize: number;
    members: Rivet.party.MemberSummary[];
    threadId: string;
}
