/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../../../environments";
import * as core from "../../../../../../core";
import { RivetApi } from "@fern-api/rivet";
import urlJoin from "url-join";
import * as serializers from "../../../../../../serialization";

export declare namespace Client {
  interface Options {
    environment?: environments.RivetApiEnvironment | string;
    token?: core.Supplier<core.BearerToken>;
  }
}

export class Client {
  constructor(private readonly options: Client.Options) {}

  public async watch(request?: RivetApi.identity.WatchEventsInput): Promise<RivetApi.identity.events.watch.Response> {
    const _queryParams = new URLSearchParams();
    if (request?.watchIndex != null) {
      _queryParams.append("watch_index", request?.watchIndex);
    }

    const _response = await core.fetcher({
      url: urlJoin(this.options.environment ?? environments.RivetApiEnvironment.Production, "/events/live"),
      method: "GET",
      headers: {
        Authorization: core.BearerToken.toAuthorizationHeader(await core.Supplier.get(this.options.token)),
      },
      queryParameters: _queryParams,
    });
    if (_response.ok) {
      return {
        ok: true,
        body: await serializers.identity.events.watch.Response.parse(
          _response.body as serializers.identity.events.watch.Response.Raw
        ),
      };
    }

    return {
      ok: false,
      error: RivetApi.identity.events.watch.Error._unknown(_response.error),
    };
  }
}
