/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Rivet } from "@rivet-gg/api";

/**
 * The current authenticated agent.
 */
export interface AuthAgent {
    identity?: Rivet.cloud.AuthAgentIdentity;
    gameCloud?: Rivet.cloud.AuthAgentGameCloud;
}
