/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface DestroyedLobbiesByFailureDataSet {
    ts: number[];
    failed: boolean[];
    destroyedLobbyCount: number[];
}
