/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface LobbyCountDataSet {
    ts: number[];
    lobbyCount: number[];
    lobbyPreemptiveCount: number[];
    lobbyUnreadyCount: number[];
    lobbyClosedCount: number[];
}
