/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { Rivet } from "@rivet-gg/api";
import * as core from "../../../../../../core";

export const GetRayPerfLogsOutput: core.serialization.ObjectSchema<
    serializers.cloud.GetRayPerfLogsOutput.Raw,
    Rivet.cloud.GetRayPerfLogsOutput
> = core.serialization.object({
    perfLists: core.serialization.property(
        "perf_lists",
        core.serialization.list(
            core.serialization.lazyObject(async () => (await import("../../../../..")).cloud.SvcPerf)
        )
    ),
});

export declare namespace GetRayPerfLogsOutput {
    interface Raw {
        perf_lists: serializers.cloud.SvcPerf.Raw[];
    }
}
