/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { RivetApi } from "@fern-api/rivet";
import * as core from "../../../../../../core";

export const PartyMatchmakerLobby: core.schemas.ObjectSchema<
  serializers.commons.PartyMatchmakerLobby.Raw,
  RivetApi.commons.PartyMatchmakerLobby
> = core.schemas.object({
  lobbyId: core.schemas.property("lobby_id", core.schemas.string()),
});

export declare namespace PartyMatchmakerLobby {
  interface Raw {
    lobby_id: string;
  }
}
