/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { RivetApi } from "@fern-api/rivet";
import * as core from "../../../../../../core";

export const PartyExternalLinks: core.serialization.ObjectSchema<
    serializers.commons.PartyExternalLinks.Raw,
    RivetApi.commons.PartyExternalLinks
> = core.serialization.object({
    chat: core.serialization.string(),
});

export declare namespace PartyExternalLinks {
    interface Raw {
        chat: string;
    }
}
