/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { RivetApi } from "@rivet-gg/api";

export interface FindLobbyOutput {
    lobby: RivetApi.commons.MatchmakerLobbyJoinInfo;
}
