/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import * as Rivet from "../../../../../../api";
import * as core from "../../../../../../core";

export const MessageBodyDeleted: core.serialization.ObjectSchema<
    serializers.chat.MessageBodyDeleted.Raw,
    Rivet.chat.MessageBodyDeleted
> = core.serialization.object({
    sender: core.serialization.lazyObject(async () => (await import("../../../../..")).identity.Handle),
});

export declare namespace MessageBodyDeleted {
    interface Raw {
        sender: serializers.identity.Handle.Raw;
    }
}
