/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { Rivet } from "@rivet-gg/api";
import * as core from "../../../../../../core";

export const MessageBodyGroupLeave: core.serialization.ObjectSchema<
    serializers.chat.MessageBodyGroupLeave.Raw,
    Rivet.chat.MessageBodyGroupLeave
> = core.serialization.object({
    identity: core.serialization.lazyObject(async () => (await import("../../../../..")).identity.Handle),
});

export declare namespace MessageBodyGroupLeave {
    interface Raw {
        identity: serializers.identity.Handle.Raw;
    }
}
