/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { Rivet } from "@rivet-gg/api";
import * as core from "../../../../../../core";

export const SendMessageBody: core.serialization.ObjectSchema<
    serializers.chat.SendMessageBody.Raw,
    Rivet.chat.SendMessageBody
> = core.serialization.object({
    text: core.serialization
        .lazyObject(async () => (await import("../../../../..")).chat.SendMessageBodyText)
        .optional(),
});

export declare namespace SendMessageBody {
    interface Raw {
        text?: serializers.chat.SendMessageBodyText.Raw | null;
    }
}
