/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { Rivet } from "@rivet-gg/api";
import * as core from "../../../../../../core";

export const SimpleTopicGroup: core.serialization.ObjectSchema<
    serializers.chat.SimpleTopicGroup.Raw,
    Rivet.chat.SimpleTopicGroup
> = core.serialization.object({
    group: core.serialization.string(),
});

export declare namespace SimpleTopicGroup {
    interface Raw {
        group: string;
    }
}
