/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { RivetApi } from "@fern-api/rivet";
import * as core from "../../../../../../core";

export const Distance: core.serialization.ObjectSchema<serializers.commons.Distance.Raw, RivetApi.commons.Distance> =
    core.serialization.object({
        kilometers: core.serialization.number(),
        miles: core.serialization.number(),
    });

export declare namespace Distance {
    interface Raw {
        kilometers: number;
        miles: number;
    }
}
