/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Rivet } from "@rivet-gg/api";

export interface GetNamespaceAnalyticsMatchmakerLiveResponse {
    /** A list of analytics lobby summaries. */
    lobbies: Rivet.cloud.AnalyticsLobbySummary[];
}
