/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { RivetApi } from "@fern-api/rivet";
import * as core from "../../../../../../core";

export const IdentityExternalLinks: core.serialization.ObjectSchema<
    serializers.commons.IdentityExternalLinks.Raw,
    RivetApi.commons.IdentityExternalLinks
> = core.serialization.object({
    profile: core.serialization.string(),
    settings: core.serialization.string().optional(),
    chat: core.serialization.string().optional(),
});

export declare namespace IdentityExternalLinks {
    interface Raw {
        profile: string;
        settings?: string | null;
        chat?: string | null;
    }
}
