/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { RivetRivet } from "@fern-api/rivet";
import * as core from "../../../../../../core";

export const IdentityStatus: core.schemas.Schema<
  serializers.commons.IdentityStatus.Raw,
  RivetRivet.commons.IdentityStatus
> = core.schemas.enum_(["online", "away", "offline"]);

export declare namespace IdentityStatus {
  type Raw = "online" | "away" | "offline";
}
