/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { Rivet } from "@rivet-gg/api";
import * as core from "../../../../../../core";

export const ActivityMatchmakerLobby: core.serialization.ObjectSchema<
    serializers.party.ActivityMatchmakerLobby.Raw,
    Rivet.party.ActivityMatchmakerLobby
> = core.serialization.object({
    lobby: core.serialization.lazyObject(async () => (await import("../../../../..")).party.MatchmakerLobby),
    game: core.serialization.lazyObject(async () => (await import("../../../../..")).game.Handle),
});

export declare namespace ActivityMatchmakerLobby {
    interface Raw {
        lobby: serializers.party.MatchmakerLobby.Raw;
        game: serializers.game.Handle.Raw;
    }
}
