/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { Rivet } from "@rivet-gg/api";
import * as core from "../../../../../../core";

export const Profile: core.serialization.ObjectSchema<serializers.party.Profile.Raw, Rivet.party.Profile> =
    core.serialization.object({
        partyId: core.serialization.property("party_id", core.serialization.string()),
        createTs: core.serialization.property("create_ts", core.serialization.date()),
        activity: core.serialization.lazyObject(async () => (await import("../../../../..")).party.Activity),
        external: core.serialization.lazyObject(async () => (await import("../../../../..")).party.ExternalLinks),
        publicity: core.serialization.lazyObject(async () => (await import("../../../../..")).party.Publicity),
        partySize: core.serialization.property("party_size", core.serialization.number().optional()),
        members: core.serialization.list(
            core.serialization.lazyObject(async () => (await import("../../../../..")).party.MemberSummary)
        ),
        threadId: core.serialization.property("thread_id", core.serialization.string()),
        invites: core.serialization.list(
            core.serialization.lazyObject(async () => (await import("../../../../..")).party.Invite)
        ),
    });

export declare namespace Profile {
    interface Raw {
        party_id: string;
        create_ts: string;
        activity: serializers.party.Activity.Raw;
        external: serializers.party.ExternalLinks.Raw;
        publicity: serializers.party.Publicity.Raw;
        party_size?: number | null;
        members: serializers.party.MemberSummary.Raw[];
        thread_id: string;
        invites: serializers.party.Invite.Raw[];
    }
}
