/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Rivet } from "@rivet-gg/api";

/**
 * CDN configuration for a given version.
 */
export interface Config {
    /** Client-side configuration */
    buildCommand?: string;
    /** Client-side configuration */
    buildOutput?: string;
    /** A universally unique identifier. */
    site?: string;
    /** Multiple CDN version routes. */
    routes?: Rivet.cloud.version.cdn.Route[];
    /** **Deprecated** */
    siteId?: string;
}
