/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Rivet } from "@rivet-gg/api";

export interface MiddlewareKind {
    customHeaders?: Rivet.cloud.version.cdn.CustomHeadersMiddleware;
}
