/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { RivetApi } from "@fern-api/rivet";

export interface ListMutualFriendsOutput {
    identities: RivetApi.commons.IdentityHandle[];
    anchor?: string;
}
