/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Rivet } from "@rivet-gg/api";

export interface ListMutualFriendsResponse {
    identities: Rivet.identity.Handle[];
    anchor?: string;
}
