/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Rivet } from "@rivet-gg/api";

export interface SearchOutput {
    identities: Rivet.identity.Handle[];
    /**
     * The pagination anchor.
     *
     */
    anchor: string;
}
