/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { Rivet } from "@rivet-gg/api";
import * as core from "../../../../../../core";

export const GetSelfProfileResponse: core.serialization.ObjectSchema<
    serializers.party.GetSelfProfileResponse.Raw,
    Rivet.party.GetSelfProfileResponse
> = core.serialization.object({
    party: core.serialization.lazyObject(async () => (await import("../../../../..")).party.Profile).optional(),
    watch: core.serialization.lazyObject(async () => (await import("../../../../..")).WatchResponse),
});

export declare namespace GetSelfProfileResponse {
    interface Raw {
        party?: serializers.party.Profile.Raw | null;
        watch: serializers.WatchResponse.Raw;
    }
}
