/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { Rivet } from "@rivet-gg/api";
import * as core from "../../../../../../core";

export const JoinResponse: core.serialization.ObjectSchema<
    serializers.party.JoinResponse.Raw,
    Rivet.party.JoinResponse
> = core.serialization.object({
    partyId: core.serialization.property("party_id", core.serialization.string()),
});

export declare namespace JoinResponse {
    interface Raw {
        party_id: string;
    }
}
