/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Rivet } from "@rivet-gg/api";

/**
 * A region that the player can connect to.
 */
export interface RegionInfo {
    regionId: Rivet.Identifier;
    providerDisplayName: string;
    regionDisplayName: string;
    datacenterCoord: Rivet.geo.Coord;
    datacenterDistanceFromClient: Rivet.geo.Distance;
}
