/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Rivet } from "@rivet-gg/api";

export interface BootstrapResponse {
    cluster: Rivet.cloud.BootstrapCluster;
    captcha: Rivet.cloud.BootstrapCaptcha;
}
