/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../..";
import { Rivet } from "@rivet-gg/api";
import * as core from "../../../../../../../../core";

export const CreateGameNamespaceTokenPublicOutput: core.serialization.ObjectSchema<
    serializers.cloud.games.namespaces.CreateGameNamespaceTokenPublicOutput.Raw,
    Rivet.cloud.games.namespaces.CreateGameNamespaceTokenPublicOutput
> = core.serialization.object({
    token: core.serialization.string(),
});

export declare namespace CreateGameNamespaceTokenPublicOutput {
    interface Raw {
        token: string;
    }
}
