/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../..";
import { Rivet } from "@rivet-gg/api";
import * as core from "../../../../../../../../core";

export const ToggleNamespaceDomainPublicAuthInput: core.serialization.ObjectSchema<
    serializers.cloud.games.namespaces.ToggleNamespaceDomainPublicAuthInput.Raw,
    Rivet.cloud.games.namespaces.ToggleNamespaceDomainPublicAuthInput
> = core.serialization.object({
    enabled: core.serialization.boolean(),
});

export declare namespace ToggleNamespaceDomainPublicAuthInput {
    interface Raw {
        enabled: boolean;
    }
}
