/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../..";
import { Rivet } from "@rivet-gg/api";
import * as core from "../../../../../../../../core";

export const UpdateGameNamespaceVersionInput: core.serialization.ObjectSchema<
    serializers.cloud.games.namespaces.UpdateGameNamespaceVersionInput.Raw,
    Rivet.cloud.games.namespaces.UpdateGameNamespaceVersionInput
> = core.serialization.object({
    versionId: core.serialization.property("version_id", core.serialization.string()),
});

export declare namespace UpdateGameNamespaceVersionInput {
    interface Raw {
        version_id: string;
    }
}
