/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Rivet from "../../../../..";

export interface GetDirectThreadResponse {
    threadId?: string;
    identity?: Rivet.identity.Handle;
}
