/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface DeleteOperationRequest {
    /**
     * A string representing a key in the key-value database. Key path components are split by a slash (e.g. `a/b/c` has the path components `["a", "b", "c"]`). Slashes can be escaped by using a forward slash (e.g. `a/b\/c/d` has the path components `["a", "b/c", "d"]`). See `rivet.api.kv.common#KeyComponents` for the structure of a `rivet.api.kv.common#Key` split by `/`.
     */
    key: string;
    namespaceId?: string;
}
