/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { RivetApi } from "@fern-api/rivet";
import * as core from "../../../../../../core";

export const GameStat: core.serialization.ObjectSchema<serializers.commons.GameStat.Raw, RivetApi.commons.GameStat> =
    core.serialization.object({
        config: core.serialization.lazyObject(async () => (await import("../../../../..")).commons.GameStatConfig),
        overallValue: core.serialization.property("overall_value", core.serialization.number()),
    });

export declare namespace GameStat {
    interface Raw {
        config: serializers.commons.GameStatConfig.Raw;
        overall_value: number;
    }
}
