/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../..";
import { Rivet } from "@rivet-gg/api";
import * as core from "../../../../../../../../core";

export const CreateGameInput: core.serialization.ObjectSchema<
    serializers.cloud.games.CreateGameInput.Raw,
    Rivet.cloud.games.CreateGameInput
> = core.serialization.object({
    nameId: core.serialization.property("name_id", core.serialization.string()),
    displayName: core.serialization.property("display_name", core.serialization.string()),
    developerGroupId: core.serialization.property("developer_group_id", core.serialization.string()),
});

export declare namespace CreateGameInput {
    interface Raw {
        name_id: string;
        display_name: string;
        developer_group_id: string;
    }
}
