/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Rivet } from "@rivet-gg/api";
import * as core from "../../../../core";

export const TransferOwnershipInput: core.serialization.ObjectSchema<
    serializers.group.TransferOwnershipInput.Raw,
    Rivet.group.TransferOwnershipInput
> = core.serialization.object({
    newOwnerIdentityId: core.serialization.property("new_owner_identity_id", core.serialization.string()),
});

export declare namespace TransferOwnershipInput {
    interface Raw {
        new_owner_identity_id: string;
    }
}
