/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Rivet } from "@rivet-gg/api";
import * as core from "../../../../core";

export const ValidateProfileOutput: core.serialization.ObjectSchema<
    serializers.group.ValidateProfileOutput.Raw,
    Rivet.group.ValidateProfileOutput
> = core.serialization.object({
    errors: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("../../..")).ValidationError)
    ),
});

export declare namespace ValidateProfileOutput {
    interface Raw {
        errors: serializers.ValidationError.Raw[];
    }
}
