/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { RivetRivet } from "@fern-api/rivet";

/**
 * A matchmaker lobby region.
 */
export interface MatchmakerLobbyJoinInfoRegion {
  regionId: RivetRivet.commons.Identifier;
  displayName: RivetRivet.commons.DisplayName;
}
