/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { RivetApi } from "@rivet-gg/api";
import * as core from "../../../../../../core";

export const MatchmakerLobbyJoinInfoRegion: core.serialization.ObjectSchema<
    serializers.commons.MatchmakerLobbyJoinInfoRegion.Raw,
    RivetApi.commons.MatchmakerLobbyJoinInfoRegion
> = core.serialization.object({
    regionId: core.serialization.property(
        "region_id",
        core.serialization.lazy(async () => (await import("../../../../..")).commons.Identifier)
    ),
    displayName: core.serialization.property(
        "display_name",
        core.serialization.lazy(async () => (await import("../../../../..")).commons.DisplayName)
    ),
});

export declare namespace MatchmakerLobbyJoinInfoRegion {
    interface Raw {
        region_id: serializers.commons.Identifier.Raw;
        display_name: serializers.commons.DisplayName.Raw;
    }
}
