/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { RivetRivet } from "@fern-api/rivet";
import * as core from "../../../../../../core";

export const MatchmakerLobbyJoinInfoPortRange: core.schemas.ObjectSchema<
  serializers.commons.MatchmakerLobbyJoinInfoPortRange.Raw,
  RivetRivet.commons.MatchmakerLobbyJoinInfoPortRange
> = core.schemas.object({
  min: core.schemas.number(),
  max: core.schemas.number(),
});

export declare namespace MatchmakerLobbyJoinInfoPortRange {
  interface Raw {
    min: number;
    max: number;
  }
}
