/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../../../..";
import * as Rivet from "../../../../../../../../../../api";
import * as core from "../../../../../../../../../../core";

export const CaptchaTurnstile: core.serialization.ObjectSchema<
    serializers.cloud.version.matchmaker.CaptchaTurnstile.Raw,
    Rivet.cloud.version.matchmaker.CaptchaTurnstile
> = core.serialization.object({
    domains: core.serialization.record(
        core.serialization.string(),
        core.serialization.lazyObject(
            async () => (await import("../../../../../../../../..")).cloud.version.matchmaker.CaptchaTurnstileDomain
        )
    ),
});

export declare namespace CaptchaTurnstile {
    interface Raw {
        domains: Record<string, serializers.cloud.version.matchmaker.CaptchaTurnstileDomain.Raw>;
    }
}
