/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { RivetIdentity } from "@fern-api/rivet-identity";
import * as core from "../../../core";

export const RateLimitError: core.schemas.Schema<serializers.RateLimitError.Raw, RivetIdentity.RateLimitError> =
  core.schemas.lazyObject(async () => (await import("../..")).RateLimitErrorResponseContent);

export declare namespace RateLimitError {
  type Raw = serializers.RateLimitErrorResponseContent.Raw;
}
