/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { Rivet } from "@rivet-gg/api";
import * as core from "../../../../../../core";

export const StartEmailVerificationInput: core.serialization.ObjectSchema<
    serializers.auth.StartEmailVerificationInput.Raw,
    Rivet.auth.StartEmailVerificationInput
> = core.serialization.object({
    email: core.serialization.string(),
    captcha: core.serialization.lazyObject(async () => (await import("../../../../..")).captcha.Config),
    gameId: core.serialization.property("game_id", core.serialization.string().optional()),
});

export declare namespace StartEmailVerificationInput {
    interface Raw {
        email: string;
        captcha: serializers.captcha.Config.Raw;
        game_id?: string | null;
    }
}
