/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { Rivet } from "@rivet-gg/api";
import * as core from "../../../../../core";

export const ReportIdentityInput: core.serialization.Schema<
    serializers.identity.ReportIdentityInput.Raw,
    Rivet.identity.ReportIdentityInput
> = core.serialization.object({
    reason: core.serialization.string(),
});

export declare namespace ReportIdentityInput {
    interface Raw {
        reason: string;
    }
}
