/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { Rivet } from "@rivet-gg/api";
import * as core from "../../../../../core";

export const SetGameActivityInput: core.serialization.Schema<
    serializers.identity.SetGameActivityInput.Raw,
    Rivet.identity.SetGameActivityInput
> = core.serialization.object({
    gameActivity: core.serialization.property(
        "game_activity",
        core.serialization.lazyObject(async () => (await import("../../../..")).identity.UpdateGameActivity)
    ),
});

export declare namespace SetGameActivityInput {
    interface Raw {
        game_activity: serializers.identity.UpdateGameActivity.Raw;
    }
}
