/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { RivetRivet } from "@fern-api/rivet";

/**
 * A group handle.
 */
export interface GroupHandle {
  groupId: string;
  displayName: RivetRivet.commons.DisplayName;
  /** The URL of this group's avatar image */
  avatarUrl: string;
  external: RivetRivet.commons.GroupExternalLinks;
  /** Whether or not this group is a developer group. */
  isDeveloper?: boolean;
}
