/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The current publicity value for the given group.
 */
export type GroupPublicity = "open" | "closed";

export const GroupPublicity = {
  Open: "open",
  Closed: "closed",
} as const;
