/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const Environment = {
  Production: "https://identity.api.rivet.gg",
} as const;

export type Environment = typeof Environment.Production;
