/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const RivetEnvironment = {
    Production: "https://api.rivet.gg",
    Staging: "https://api.staging.gameinc.io",
} as const;

export type RivetEnvironment = typeof RivetEnvironment.Production | typeof RivetEnvironment.Staging;
