/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { RivetApi } from "@fern-api/rivet";

/**
 * A game mode that the player can join.
 */
export interface GameModeInfo {
    gameModeId: RivetApi.commons.Identifier;
}
