/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * External links for an identity.
 */
export interface IdentityExternalLinks {
  /** A link to this identity's profile page. */
  profile: string;
  /** A link to the Rivet settings page. */
  settings?: string;
  /** A link to a chat page with the given identity. */
  chat?: string;
}
