/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { RivetRivet } from "@fern-api/rivet";

/**
 * An identity profile.
 */
export interface IdentityProfile {
  identityId: string;
  displayName: RivetRivet.commons.DisplayName;
  accountNumber: RivetRivet.commons.AccountNumber;
  /** The URL of this identity's avatar image. */
  avatarUrl: string;
  presence?: RivetRivet.commons.IdentityPresence;
  /** Whether or not this identity is registered with a linked account. */
  party?: RivetRivet.commons.PartySummary;
  /** Whether or not this identity is registered with a linked account. */
  isRegistered: boolean;
  external: RivetRivet.commons.IdentityExternalLinks;
  /** Whether or not this identity is an admin. */
  isAdmin: boolean;
  /** Whether or not this game user has been linked through the Rivet dashboard. */
  isGameLinked?: boolean;
  devState?: RivetRivet.commons.IdentityDevState;
  followerCount: number;
  followingCount: number;
  /** Whether or not the requestee's identity is following this identity. */
  following: boolean;
  /** Whether or not this identity is both followng and is followed by the requestee's identity. */
  isFollowingMe: boolean;
  isMutualFollowing: boolean;
  joinTs: RivetRivet.commons.Timestamp;
  bio: RivetRivet.commons.Bio;
  linkedAccounts: RivetRivet.commons.IdentityLinkedAccount[];
  groups: RivetRivet.commons.IdentityGroup[];
  games: RivetRivet.commons.GameStatSummary[];
}
