/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { RivetRivet } from "@fern-api/rivet";

/**
 * An identity summary.
 */
export interface IdentitySummary {
  identityId: string;
  displayName: RivetRivet.commons.DisplayName;
  accountNumber: RivetRivet.commons.AccountNumber;
  /** The URL of this identity's avatar image. */
  avatarUrl: string;
  presence?: RivetRivet.commons.IdentityPresence;
  party?: RivetRivet.commons.PartyHandle;
  /** Whether or not this identity is registered with a linked account. */
  isRegistered: boolean;
  external: RivetRivet.commons.IdentityExternalLinks;
  /** Whether or not the requestee's identity is following this identity. */
  following: boolean;
  /** Whether or not this identity is both followng and is followed by the requestee's identity. */
  isFollowingMe: boolean;
  isMutualFollowing: boolean;
}
