/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { RivetRivet } from "@fern-api/rivet";

/**
 * An identity's linked email.
 */
export interface IdentityEmailLinkedAccount {
  email: RivetRivet.commons.Email;
}
