/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { RivetIdentity } from "@fern-api/rivet-identity";
import * as core from "../../../core";

export const Email: core.schemas.Schema<serializers.Email.Raw, RivetIdentity.Email> = core.schemas.string();

export declare namespace Email {
  type Raw = string;
}
