/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { RivetIdentity } from "@fern-api/rivet-identity";
import * as core from "../../../core";

export const GameHandle: core.schemas.ObjectSchema<serializers.GameHandle.Raw, RivetIdentity.GameHandle> =
  core.schemas.object({
    gameId: core.schemas.property("game_id", core.schemas.string()),
    nameId: core.schemas.property(
      "name_id",
      core.schemas.lazy(async () => (await import("../..")).Identifier)
    ),
    displayName: core.schemas.property(
      "display_name",
      core.schemas.lazy(async () => (await import("../..")).DisplayName)
    ),
    logUrl: core.schemas.property("log_url", core.schemas.string().optional()),
    bannerUrl: core.schemas.property("banner_url", core.schemas.string().optional()),
  });

export declare namespace GameHandle {
  interface Raw {
    game_id: string;
    name_id: serializers.Identifier.Raw;
    display_name: serializers.DisplayName.Raw;
    log_url?: string | null;
    banner_url?: string | null;
  }
}
