/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { RivetIdentity } from "@fern-api/rivet-identity";
import * as core from "../../../core";

export const GroupExternalLinks: core.schemas.ObjectSchema<
  serializers.GroupExternalLinks.Raw,
  RivetIdentity.GroupExternalLinks
> = core.schemas.object({
  profile: core.schemas.string(),
  chat: core.schemas.string(),
});

export declare namespace GroupExternalLinks {
  interface Raw {
    profile: string;
    chat: string;
  }
}
