/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { RivetIdentity } from "@fern-api/rivet-identity";
import * as core from "../../../core";

export const IdentityDevState: core.schemas.Schema<serializers.IdentityDevState.Raw, RivetIdentity.IdentityDevState> =
  core.schemas.string();

export declare namespace IdentityDevState {
  type Raw = string;
}
