/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { RivetIdentity } from "@fern-api/rivet-identity";
import * as core from "../../../core";

export const PartyExternalLinks: core.schemas.ObjectSchema<
  serializers.PartyExternalLinks.Raw,
  RivetIdentity.PartyExternalLinks
> = core.schemas.object({
  chat: core.schemas.string(),
});

export declare namespace PartyExternalLinks {
  interface Raw {
    chat: string;
  }
}
