/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { Rivet } from "@rivet-gg/api";
import * as core from "../../../../../../core";

export const GroupBillingCheckoutResponse: core.serialization.ObjectSchema<
    serializers.cloud.GroupBillingCheckoutResponse.Raw,
    Rivet.cloud.GroupBillingCheckoutResponse
> = core.serialization.object({
    url: core.serialization.string(),
});

export declare namespace GroupBillingCheckoutResponse {
    interface Raw {
        url: string;
    }
}
